export const types = {
  ADD_EDGE: "ADD_EDGE",
  DELETE_EDGE: "DELETE_EDGE",
  ADD_NODE: "ADD_NODE",
  DELETE_NODE: "DELETE_NODE",
  CLEAR_NETWORK: "CLEAR_NETWORK",
  ADD_NODES: "ADD_NODES",
  ADD_EDGES: "ADD_EDGES",
  EDIT_NODE: "EDIT_NODE",
};
